// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6XgPt1u8aJK03Y7OGXnudH6jvY9qu1Og',
    appId: '1:1093664415469:web:e824ef033d3ed0496ab6e4',
    messagingSenderId: '1093664415469',
    projectId: 'glc-main-125d7',
    authDomain: 'glc-main-125d7.firebaseapp.com',
    storageBucket: 'glc-main-125d7.appspot.com',
    measurementId: 'G-6WP97KBJMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLDGqACZXYujH8vkIhjcyDf11VxAK_BZs',
    appId: '1:1093664415469:android:94b9f7f434c66f016ab6e4',
    messagingSenderId: '1093664415469',
    projectId: 'glc-main-125d7',
    storageBucket: 'glc-main-125d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBHa7cjpDesYJopBKmp49tgNyLtDX7fC0',
    appId: '1:1093664415469:ios:00f742d2c0df9ea66ab6e4',
    messagingSenderId: '1093664415469',
    projectId: 'glc-main-125d7',
    storageBucket: 'glc-main-125d7.appspot.com',
    iosClientId:
        '1093664415469-ed6bg1v2plbi6anjjbda6k4kbgdpv66l.apps.googleusercontent.com',
    iosBundleId: 'com.onyekachi.godLifeConversations',
  );
}
